### PR TITLE
Fix a typo and add a % for string format

### PR DESCRIPTION
**Pull request by masoudd**

### CODE REVIEW

**Review by hartwork — APPROVED** [review]
@gbtami good to merge?

**Review by hartwork — CHANGES_REQUESTED** [review]
Sorry, I overlooked the red CI. It needs this change for a green CI (ignoring the Windows build):

```diff
 -            "Gtk version is %s.%s.%s" %
-            (Gtk.MAJOR_VERSION, Gtk.MINOR_VERSION, Gtk.MICRO_VERSION),
+            "Gtk version is %s.%s.%s"
+            % (Gtk.MAJOR_VERSION, Gtk.MINOR_VERSION, Gtk.MICRO_VERSION),
```

See https://github.com/pychess/pychess/actions/runs/8840365479/job/24275551382#step:4:137

**Comment by masoudd** [comment]
Sorry for not checking code formatting before committing.

**Comment by gbtami** [comment]
Thx.

**Pull request merged**
