### PR TITLE
prefix.py: Avoid false positives and negatives from "in __file__"

### PR DESCRIPTION
**Pull request by hartwork**
Started out at https://github.com/pychess/pychess/pull/2038#issuecomment-1513221139

### CODE REVIEW

**Comment by hartwork** [comment]
@gbtami please note that GitHub Actions seems to struggle at the moment, not all pushes seem to trigger the CI. Let's give it a few minutes to see if it heals itself.

**Comment by gbtami** [comment]
`TypeError: realpath() got an unexpected keyword argument 'strict'`

From Python docs:
Changed in version 3.10: The strict parameter was added.

**Comment by hartwork** [comment]
@gbtami yes, already fixed that. And CI is finally running…

**Comment by hartwork** [comment]
And another round with fixes [for Windows](https://github.com/hartwork/pychess/actions/runs/4733924097/jobs/8402128887#step:6:32)…

**Review by gbtami — APPROVED** [review]

**Comment by hartwork** [comment]
@gbtami thanks for the review! :+1:

**Pull request merged**
