### PR TITLE
new command line argument

### PR DESCRIPTION
**Pull request by gideon425**
The changes implement a new command line argument --auto_save_pgn_file

### CODE REVIEW

**Comment by mattgatto** [comment]
Why not just save games automatically? I don't see the point of a command
option for this.

**Comment by mattgatto** [comment]
We should consider just getting rid of the save dialog and just do this
automatically unless someone can think of a reason to do otherwise, in my
opinion.

**Comment by gbtami** [comment]
I'm fine with getting rid of save dialog. Telling the truth I hate to close it every time I'm pychessing. But if we do that, we have to add some preferences option Thomas mentioned in the original issue #256. At least until we integrate the database stuff into the new GUI redesign.

**Comment by gideon425** [comment]
I am open to modifying my changes.  I suggest we continue the discussion in issue 256. I will update that issue with my thinking

**Pull request merged**
