### PR TITLE
Reworked UI and PGN export for tag editor

### PR DESCRIPTION
**Pull request by ecrucru**
Changes for #1581 :
- New properties of the game with a blank editor (step 1)
- Update of the tags (step 2)
- Export to PGN (step 5)

The issue will be updated to follow the changes.

### CODE REVIEW

**Comment by gbtami** [comment]
May I ask you to move add/remove buttons below the treeview on additional tags tab please? I think it will be more consistent with other PyChess dialogue layouts that way. Btw. I feel the same problem seeing sub-fen entry and copy/paste buttons on database filters dialogue.

**Comment by ecrucru** [comment]
The PR is updated.

**Comment by gbtami** [comment]
Thx!
I think this is OK for 1. and 5., but without 2. 3. and 4. of https://github.com/pychess/pychess/issues/1581 it is half baked only. At least for read only (meaning no add/delete/edit of extra tags) version of extra tags handling needs 3. and 4. to be implemented.

**Comment by ecrucru** [comment]
The steps 1, 2 (now added) and 5 are completed within this PR. I will definitely need your contribution to handle the steps 3 and 4, please.

I left in the code some TODO to see what we can do to remove `Year`, `Month`, `Day`, `Time`. I have the impression that they should not be part of the tags, so their names are hardcoded for now in the export to PGN. They may also be displayed in the tag editor, it can look strange.

**Comment by gbtami** [comment]
Thx!

**Pull request merged**
