### PR TITLE
Add the engines in mass from UI

### PR DESCRIPTION
**Pull request by ecrucru**
Hello gbtami,

This PR aims to provide the second part of the solution for #1642.

Thanks for your comments.

Regards

### CODE REVIEW

**Comment by gbtami** [comment]
The new mass_list_treeview should be inside a GtkScrolledWindow because if I choose my engines folder it picks up a looong list of engines. Not all can be shown on my screen. Not to mention that I can't select Ok, Cancel buttons because they are out of screen also.

Travis CI failed because id of `<object class="GtkTreeSelection"/>` is missing at line #5626 in PyChess.glade
```
Traceback (most recent call last):
  File "/home/travis/build/pychess/pychess/testing/database.py", line 12, in setUp
    widgets = uistuff.GladeWidgets("PyChess.glade")
  File "/home/travis/build/pychess/pychess/lib/pychess/System/uistuff.py", line 441, in __init__
    self.builder.add_from_file(addDataPrefix("glade/%s" % filename))
gi._glib.GError: /home/travis/build/pychess/pychess/glade/PyChess.glade:5626:53 <object> requires attribute "id"
```

**Comment by ecrucru** [comment]
OK, it should be much better now.

Thanks.

**Comment by gbtami** [comment]
Great! Thx.

**Comment by gbtami** [comment]
One thing I noticed and can be enhanced is to make "unknown" (not in `engineList.py`) engine detection a little bit more robust. I mean use `is_uci()` and `is_cecp()` in `addInMass()` similar as used in `add()`
Now addInMass added garbochess.py engine to installed engines list, but it is nor uci nor cecp and unusable with PyChess :)

**Pull request merged**
