### PR TITLE
Open remote games

### PR DESCRIPTION
**Pull request by ecrucru**
Following #1751 to make flake8 happy :)

### CODE REVIEW

**Comment by gbtami** [comment]
Thx!

**Comment by ecrucru** [comment]
As usual, I was finalizing the fixes with Travis' output. But few commits are left in my branch, you already correct one error.
May you have a look to my branch dev_dl2 to apply the last changes on your side ? The commits are now conflicting.
Thanks

**Comment by gbtami** [comment]
@ecrucru done.
But somehow chess.org test is still failing for me:
```
Chess.org -- Websockets
- Target link : https://CHESS.org/play/c28f1b76-aee0-4577-b8a5-eeda6a0e14af
- Expecting data : True
- Fetched data : False
F
```

**Comment by ecrucru** [comment]
OK thanks.
This game is loading in the foreground and background. I can't reproduce the error :(

**Comment by gbtami** [comment]
@ecrucru now it fails on first chess.org test case https://travis-ci.org/pychess/pychess
```
Chess.org -- Websockets
- Target link : https://chess.org/play/19a8ffe8-b543-4a41-be02-e84e0f4d6f3a
- Expecting data : True
- Fetched data : False
F
```

```
======================================================================
FAIL: testChessOrg (remotegame.RemoteGameTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 97, in testChessOrg
    self.executeTest(InternetGameChessOrg(), links)
  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 25, in executeTest
    self.assertEqual(ok, expected)
AssertionError: False != True
----------------------------------------------------------------------
Ran 832 tests in 416.510s
FAILED (failures=1)
The command "PYTHONPATH=../lib xvfb-run -a coverage run --omit=../lib/pychess/external/* --source ../lib -m unittest discover -p "*.py"" exited with 1.
```

**Pull request merged**
