### PR TITLE
Open URL

### PR DESCRIPTION
**Pull request by ecrucru**
Hello,

This PR solves #1690. By giving the URL, you can load a finished remote game into PyChess as a new game.

Can you help to regenerate the POT file after ?

Thanks.

### CODE REVIEW

**Comment by gbtami** [comment]
Doesn't work for me with https://lichess.org/study/hr4H7sOB.pgn

**Comment by gbtami** [comment]
For me unit test produces 1 error.

ChessTempo.com -- Download link
- Target link : http://chesstempo.com
- Expecting data : False
- Fetched data : True
F
======================================================================
FAIL: test (__main__.RemoteGameTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "remotegame.py", line 24, in test
    self.assertEqual(ok, expected)
AssertionError: True != False

----------------------------------------------------------------------
Ran 1 test in 2.023s

FAILED (failures=1)

**Comment by gbtami** [comment]
All test data (all get_test_links()) belongs to unittest. Can you move them there, please?

**Comment by ecrucru** [comment]
Hello,

Lichess studies were not implemented yet.

For ChessTempo, a precondition failed out of the class due to a wrong piece of code. The test case is adjusted accordingly.

For `unittest`, the URL to fetch depend on the classes activated in `chess_providers`. So it doesn't make sense to me to put the test URL out of their classes. Do you see another solution ?

HaGN

**Comment by gbtami** [comment]
You can make individual test cases for different chess_providers something like movegen tests here https://github.com/pychess/pychess/blob/master/testing/movegen.py#L151

If you like extreme data driven approach you can go for something like this https://github.com/mcostalba/scoutfish/blob/master/src/test.py

While the latter seems more elegant, the former is much simpler and fits better to Zen of Python: Explicit is better then implicit :)

**Comment by gbtami** [comment]
Cool, thx a lot!

**Pull request merged**
