### PR TITLE
Remove all files in pieces/ttf/*.ttf

### LINKED ISSUE #1930: double pieces
in the last version, some parts are duplicated.

image

### PR DESCRIPTION
**Pull request by masoudd**
if the pieces/ttf directory itself is deleted then
the create_theme_preview.py fails.
I can edit that script to fully delete all traces of the ttf directory if needed.

Closes #1930

### CODE REVIEW

**Comment by masoudd** [comment]
There is also some ttf and cairo related logic in `lib/pychess/gfx/Pieces.py` like [get_chess_font_face(name)](https://github.com/pychess/pychess/blob/e3f9b12947e429993edcc2b9288f79bc181e6500/lib/pychess/gfx/Pieces.py#L124) and

[if piece_set.startswith("ttf-"):](https://github.com/pychess/pychess/blob/e3f9b12947e429993edcc2b9288f79bc181e6500/lib/pychess/gfx/Pieces.py#L160)

Should I rip it all out or just leave it be?

**Comment by gbtami** [comment]
Yea, we should remove all ttf related code as well I think.

**Comment by masoudd** [comment]
removed around 200 lines. I am unsure about the changes in `setup.py`. Please check if it's ok

**Comment by gbtami** [comment]
Thx!

**Pull request merged**
