### PR TITLE
Update pychess.po

### PR DESCRIPTION
**Pull request by ghost**
little French mistake

### CODE REVIEW

**Comment by gbtami** [comment]
Pychess uses Transifex for translations. Go to https://www.transifex.com/projects/p/pychess/ please! Thx.

**Comment by sshivaji** [comment]
Laripette is right in this case as checkmate is a sudden and connected
action and not something that was there for a long time.

Is the solution to go to transifex and fix these strings?

Thanks!

**Comment by gbtami** [comment]
Yes. See https://github.com/pychess/pychess/wiki/TransifexTranslates

Transifex is the source of our translations. Once per day transifex auto merges from https://github.com/pychess/pychess/blob/master/lang/pychess.pot
Translators work on it on transifex web GUI, and before releases (or occasionally) I pull new translations from there to our github.

Here is a screenshot how it looks like on transifex

**Comment by sshivaji** [comment]
Thanks, will follow up, ideally, Laripette can fix it on Transifex. Even
though French is not my native language, Parce and était are quite annoying
to read! :)

**Comment by ghost** [comment]
I don't have a transifex account, if someone could correct the mistake for me.

thank you

**Pull request closed without merging**
