### PR TITLE
Collective changes

### PR DESCRIPTION
**Pull request by ecrucru**
Hello

Please find the following changes:
- update for the remote games
- updated list of engines
- fix copyright year
- fix escape key in annotationPanel that incorrectly validates data
- fix an error when pressing enter over the board

Have a good week

### CODE REVIEW

**Comment by gbtami** [comment]
Thx!

**Comment by gbtami** [comment]
Hi after merge Travis is throwing unit test errors. Can you take a look please?
```
======================================================================

FAIL: testChessOrg (remotegame.RemoteGameTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 115, in testChessOrg

    self.executeTest(InternetGameChessOrg(), links)

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 34, in executeTest

    self.assertEqual(ok, expected)

AssertionError: False != True

======================================================================

FAIL: testChessdb (remotegame.RemoteGameTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 247, in testChessdb

    self.executeTest(InternetGameChessdb(), links)

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 34, in executeTest

    self.assertEqual(ok, expected)

AssertionError: False != True

======================================================================

FAIL: testChesstempo (remotegame.RemoteGameTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 80, in testChesstempo

    self.executeTest(InternetGameChesstempo(), links)

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 34, in executeTest

    self.assertEqual(ok, expected)

AssertionError: False != True

======================================================================

FAIL: testPychess (remotegame.RemoteGameTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 286, in testPychess

    self.executeTest(InternetGamePychess(), links)

  File "/home/travis/build/pychess/pychess/testing/remotegame.py", line 34, in executeTest

    self.assertEqual(ok, expected)

AssertionError: False != True

----------------------------------------------------------------------

Ran 863 tests in 356.336s

FAILED (failures=4)
```

**Comment by ecrucru** [comment]
For ChessDB, there is a missing return in the unit test below "Skipping disabled chess provider". Can you add it for me ?

For the other classes, they are based on websockets. The event loop is still an issue on Linux-based systems (see the remaining TODO in the code). The games are loaded correctly with the Windows version of PyChess. I also verified the code with a console version under Linux : there no issue in the download logic. It is possible to turn off the affected classes under Linux, but it used to work in console mode (so in Travis too). I have no idea yet :(

**Comment by gbtami** [comment]
Done.

**Pull request merged**
