### PR TITLE
Extended list of engines

### PR DESCRIPTION
**Pull request by ecrucru**
Hello,

Here is the extended list of reliable engines that can be detected.
It provides accurate default values, and it may serve for the enhancement #1642.

Regards

### CODE REVIEW

**Comment by gbtami** [comment]
As I said before I don't want to maintain an ever growing and changing list of engines in pychess.

**Comment by gbtami** [comment]
@ecrucru First of all, sorry if I seemed too negative. As I think today my only concern regarding this PR is slow startup time of PyChess. But if this PR is just to help implement #1642 and doesn't affect auto querying distribution installed engines on pychess startup, I'm fine with it.
Maybe after stockfish being official dependency of pychess, we should drop checking distribution installed engines (at least the part what is based on our hardwired list, but preserve HGM method!) on pychess startup. What do you think?

**Comment by ecrucru** [comment]
Hello, I am happy that you finally realized the indirect interest of that PR. I still use it personally from the time it was posted and I don't see any issue with it. It might need some optimization indeed.

To handle the adding in mass of the engines, the checklist could be :
- the default auto-detect with full list is done once at start-up by config
- the default auto-detect is trigerable from engineDialog : it will scan the environment PATH, plus some hard paths like `/usr/bin/games`
- add in mass with full list from new "Add folder" : it will not scan PATH but 2 or 3 sub-levels of the selected folder
- the find of shutil should be replaced by something supporting wildcards, bitness, file attribute, pattern of exclusion for file names, cpuid, paths out of/in complement of the environment PATH... That's hard, please refer to the other issue
- adapt the unit tests so that travis detects the file "stockfish_9_x32.exe" by just giving "stockfish"
- check if the HGM method is still applicable

Theoretically, the list works both for Windows and Linux if we don't specify something like "stockfish_9_x32.exe".

**Comment by gbtami** [comment]
If you still interested on #1642 may I ask you to re send this PR, please?

**Pull request closed without merging**
